# API Module - This should trigger violations
# AI GENERATED/UPDATED CODE - Added by Claude Code
# Second update by Claude Code to test detection
from flask import Flask, jsonify, request

app = Flask(__name__)

@app.route('/users', methods=['GET'])
def get_users():
    """Get all users from database"""
    users = [
        {"id": 1, "name": "Alice"},
        {"id": 2, "name": "Bob"},
        {"id": 3, "name": "Charlie"}
    ]
    return jsonify(users)

print("Hello there")
print("Thjis is an experiment for testing")

# ==================== THIRD BATCH - DEMO VIDEO ====================
@app.route('/users/stats', methods=['GET'])
def get_stats():
    """Get user statistics - AI Generated for demo"""
    users = [
        {"id": 1, "name": "Alice", "active": True},
        {"id": 2, "name": "Bob", "active": False},
        {"id": 3, "name": "Charlie", "active": True}
    ]
    total = len(users)
    active = sum(1 for u in users if u["active"])
    return jsonify({
        "total_users": total,
        "active_users": active,
        "inactive_users": total - active
    })
# ==================== END THIRD BATCH ====================

@app.route('/users/<int:user_id>', methods=['GET'])
def get_user(user_id):
    """Get a single user by ID - AI Generated"""
    users = [
        {"id": 1, "name": "Alice"},
        {"id": 2, "name": "Bob"},
        {"id": 3, "name": "Charlie"}
    ]
    user = next((u for u in users if u["id"] == user_id), None)
    if user:
        return jsonify(user)
    return jsonify({"error": "User not found"}), 404

@app.route('/health', methods=['GET'])
def health_check():
    """Health check endpoint - AI Generated"""
    return jsonify({"status": "healthy", "version": "1.0.0"})

@app.route('/users', methods=['POST'])
def create_user():
    """Create a new user - AI Generated endpoint"""
    data = request.get_json()
    if not data or 'name' not in data:
        return jsonify({"error": "Name is required"}), 400
    new_user = {
        "id": 4,
        "name": data['name']
    }
    return jsonify(new_user), 201

@app.route('/users/<int:user_id>', methods=['DELETE'])
def delete_user(user_id):
    """Delete a user by ID - AI Generated endpoint"""
    return jsonify({"message": f"User {user_id} deleted"}), 200

# ==================== NEW CODE ADDED BY CLAUDE CODE ====================
# Testing diff logging in on_moved handler
@app.route('/users/<int:user_id>', methods=['PUT'])
def update_user(user_id):
    """Update user information - AI Generated endpoint"""
    data = request.get_json()
    if not data:
        return jsonify({"error": "No data provided"}), 400

    updated_user = {
        "id": user_id,
        "name": data.get('name', 'Unknown'),
        "email": data.get('email', ''),
        "updated": True
    }
    return jsonify(updated_user), 200
# ==================== END NEW CODE ====================

# ==================== FOURTH BATCH - SOURCE TRACKING TEST ====================
@app.route('/users/bulk', methods=['POST'])
def bulk_create_users():
    """Bulk create multiple users - AI Generated for source tracking test"""
    data = request.get_json()
    if not data or 'users' not in data:
        return jsonify({"error": "Users array is required"}), 400

    created_users = []
    for i, user_data in enumerate(data['users']):
        new_user = {
            "id": 100 + i,
            "name": user_data.get('name', f'User_{i}'),
            "email": user_data.get('email', ''),
            "created_by": "bulk_api"
        }
        created_users.append(new_user)

    return jsonify({
        "created": len(created_users),
        "users": created_users
    }), 201
# ==================== END FOURTH BATCH ====================

# ==================== SECOND BATCH - TESTING DIFF LOGGING ====================
@app.route('/users/search', methods=['GET'])
def search_users():
    """Search users by name - AI Generated endpoint for testing diff logging"""
    query = request.args.get('q', '')
    users = [
        {"id": 1, "name": "Alice"},
        {"id": 2, "name": "Bob"},
        {"id": 3, "name": "Charlie"}
    ]
    results = [u for u in users if query.lower() in u["name"].lower()]
    return jsonify({"query": query, "results": results, "count": len(results)})
# ==================== END SECOND BATCH ====================

# ==================== FIFTH BATCH - CLAUDE CODE AI TEST ====================
@app.route('/users/analytics', methods=['GET'])
def get_user_analytics():
    """Get detailed user analytics - AI Generated by Claude Code"""
    users = [
        {"id": 1, "name": "Alice", "active": True, "logins": 45},
        {"id": 2, "name": "Bob", "active": False, "logins": 12},
        {"id": 3, "name": "Charlie", "active": True, "logins": 89},
        {"id": 4, "name": "Diana", "active": True, "logins": 34},
        {"id": 5, "name": "Eve", "active": False, "logins": 5}
    ]

    total_users = len(users)
    active_users = sum(1 for u in users if u["active"])
    total_logins = sum(u["logins"] for u in users)
    avg_logins = total_logins / total_users if total_users > 0 else 0

    return jsonify({
        "total_users": total_users,
        "active_users": active_users,
        "inactive_users": total_users - active_users,
        "total_logins": total_logins,
        "average_logins": round(avg_logins, 2),
        "most_active": max(users, key=lambda u: u["logins"])["name"]
    })
# ==================== END FIFTH BATCH ====================
print("hello world")
# ==================== SIXTH BATCH - CLAUDE CODE AI TEST ====================
@app.route('/users/export', methods=['GET'])
def export_users():
    """Export users to different formats - AI Generated by Claude Code"""
    format_type = request.args.get('format', 'json')
    users = [
        {"id": 1, "name": "Alice", "email": "alice@example.com"},
        {"id": 2, "name": "Bob", "email": "bob@example.com"},
        {"id": 3, "name": "Charlie", "email": "charlie@example.com"},
        {"id": 4, "name": "Diana", "email": "diana@example.com"},
        {"id": 5, "name": "Eve", "email": "eve@example.com"}
    ]

    if format_type == 'csv':
        csv_data = "id,name,email\n"
        for user in users:
            csv_data += f"{user['id']},{user['name']},{user['email']}\n"
        return csv_data, 200, {'Content-Type': 'text/csv'}

    return jsonify({"format": format_type, "users": users, "count": len(users)})
# ==================== END SIXTH BATCH ====================

# ==================== SEVENTH BATCH - USAGE TRACKING TEST ====================
@app.route('/users/metrics', methods=['GET'])
def get_user_metrics():
    """Get comprehensive user metrics - AI Generated by Claude Code"""
    period = request.args.get('period', 'daily')
    users = [
        {"id": 1, "name": "Alice", "signups": 5, "revenue": 150.00},
        {"id": 2, "name": "Bob", "signups": 3, "revenue": 89.50},
        {"id": 3, "name": "Charlie", "signups": 8, "revenue": 245.00},
        {"id": 4, "name": "Diana", "signups": 2, "revenue": 67.25},
        {"id": 5, "name": "Eve", "signups": 6, "revenue": 178.75}
    ]

    total_signups = sum(u["signups"] for u in users)
    total_revenue = sum(u["revenue"] for u in users)
    avg_revenue = total_revenue / len(users) if users else 0

    return jsonify({
        "period": period,
        "total_signups": total_signups,
        "total_revenue": round(total_revenue, 2),
        "average_revenue": round(avg_revenue, 2),
        "top_performer": max(users, key=lambda u: u["revenue"])["name"]
    })
# ==================== END SEVENTH BATCH ====================

print("this is a log test")
print("This is a test for branch dev2")

# ==================== DEV2 BATCH - TASK MANAGEMENT ====================
@app.route('/tasks', methods=['GET'])
def get_tasks():
    """Get all project tasks - added on dev2 branch"""
    status_filter = request.args.get('status', 'all')
    tasks = [
        {"id": 1, "title": "Setup CI/CD pipeline", "status": "completed", "assignee": "Alice", "priority": "high"},
        {"id": 2, "title": "Write unit tests", "status": "in_progress", "assignee": "Bob", "priority": "high"},
        {"id": 3, "title": "Update documentation", "status": "pending", "assignee": "Charlie", "priority": "medium"},
        {"id": 4, "title": "Code review sprint 3", "status": "in_progress", "assignee": "Diana", "priority": "high"},
        {"id": 5, "title": "Deploy to staging", "status": "pending", "assignee": "Eve", "priority": "low"},
    ]
    if status_filter != 'all':
        tasks = [t for t in tasks if t["status"] == status_filter]
    return jsonify({
        "tasks": tasks,
        "total": len(tasks),
        "filter": status_filter
    })
# ==================== END DEV2 BATCH ====================

if __name__ == '__main__':
    app.run(debug=True)
